//! Markdown + JSON report rendering for H1–H5．
//!
//! Reports are user-facing analysis deliverables produced at runtime; they
//! intentionally carry **no** "generated by Claude" footer．

use std::fmt::Write as _;
use std::path::Path;

use serde::Serialize;

use crate::anonymize::Anonymizer;
use crate::error::Result;
use crate::figures;
use crate::graph::ReplyGraph;
use crate::models::{CommReport, H1Metrics, H2Metrics, H3Metrics, H4Metrics, H5Metrics};

const NA_NLP: &str = "N/A (NLP sidecar 無効/未起動)";
const ETHICS_NOTE: &str = "本ツールは組織構造の歪み発見のためのものであり個人評価・懲罰用途に転用してはならない．集計値のみを示す．";

#[derive(Serialize)]
struct ReportJson<'a, M: Serialize> {
    hypothesis: &'a str,
    period: &'a str,
    channels: usize,
    messages: usize,
    metrics: &'a M,
}

fn write_files<M: Serialize>(
    dir: &Path,
    hypothesis: &str,
    period: &str,
    n_channels: usize,
    n_messages: usize,
    metrics: &M,
    md: &str,
) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("report.md"), md)?;
    let json = ReportJson {
        hypothesis,
        period,
        channels: n_channels,
        messages: n_messages,
        metrics,
    };
    let pretty = serde_json::to_string_pretty(&json)
        .map_err(|e| crate::error::CommError::Config(e.to_string()))?;
    std::fs::write(dir.join("metrics.json"), pretty)?;
    Ok(())
}

fn header(title: &str, label: &str, n_channels: usize, n_messages: usize) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# {title}\n");
    let _ = writeln!(s, "- 期間: {label}");
    let _ = writeln!(s, "- 対象チャネル: {n_channels}個");
    let _ = writeln!(s, "- 対象メッセージ: {n_messages}件\n");
    s
}

/// Write `report.md` + `metrics.json` for the H2 hypothesis．
pub fn write_h2_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    m: &H2Metrics,
) -> Result<()> {
    let mut md = header("H2: 心理的安全性レポート", label, n_channels, n_messages);
    let _ = writeln!(md, "## 指標\n");
    let _ = writeln!(md, "| 指標 | 値 | 解釈 |");
    let _ = writeln!(md, "|------|----|------|");
    let _ = writeln!(
        md,
        "| ヘッジ表現率 | {:.4} | 高いほど自己防衛的な前置きが多く心理的安全性が低い可能性 |",
        m.hedging_rate
    );
    let _ = writeln!(
        md,
        "| 自己防衛表現率 | {:.4} | 高いほど発言前の予防線が多い |",
        m.self_defense_rate
    );
    let _ = writeln!(
        md,
        "| 未完結発話率 | {:.4} | 高いほど言い淀み・中断が多い |",
        m.incomplete_utterance_rate
    );
    let _ = writeln!(
        md,
        "| エスカレーション遅延(分) | {:.2} | 障害検知から他者共有までの中央値 |",
        m.escalation_delay_minutes
    );
    let dm = match m.dm_dependency_ratio {
        Some(v) => format!("{:.4}", v),
        None => "N/A".to_string(),
    };
    let _ = writeln!(md, "| DM依存度 | {dm} | 未算出 |");
    let _ = writeln!(
        md,
        "| サンプル数 | {} | 集計対象メッセージ数 |\n",
        m.sample_size
    );

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");

    write_files(dir, "H2", label, n_channels, n_messages, m, &md)
}

/// Write `report.md` + `metrics.json` for the H3 hypothesis．
pub fn write_h3_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    m: &H3Metrics,
    top: usize,
) -> Result<()> {
    let mut md = header("H3: 権力勾配レポート", label, n_channels, n_messages);

    let _ = writeln!(md, "## 主要指標\n");
    let _ = writeln!(md, "| 指標 | 値 | 解釈 |");
    let _ = writeln!(md, "|------|----|------|");
    let _ = writeln!(
        md,
        "| 返信集中Gini | {:.4} | 1に近いほど返信が一部に集中 |",
        m.reply_concentration_gini
    );
    let _ = writeln!(
        md,
        "| マネージャ反応率 | {:.4} | 管理職メッセージへの同意リアクション密度 |",
        m.manager_reaction_rate
    );
    let _ = writeln!(
        md,
        "| 反論バイアス(対管理職) | {:.4} | 管理職宛て返信のうち反論を含む割合 |",
        m.dissent_target_bias.to_manager
    );
    let _ = writeln!(
        md,
        "| 反論バイアス(対スタッフ) | {:.4} | スタッフ宛て返信のうち反論を含む割合 |",
        m.dissent_target_bias.to_staff
    );
    let _ = writeln!(
        md,
        "| 反論比(スタッフ/管理職) | {:.4} | 1未満は管理職へ反論しにくい兆候 |",
        m.dissent_target_bias.ratio_staff_to_manager
    );
    let _ = writeln!(
        md,
        "| 階層スコア | {:.4} | 1.0=完全DAG/階層的，低いほど相互的/フラット |",
        m.hierarchy_score
    );
    let _ = writeln!(
        md,
        "| PageRank上位の管理職占有率 | {:.4} | 上位中心ノードに占める管理職割合 |\n",
        m.pagerank_topk_manager_share
    );

    let mut conc = m.normalized_concentration.clone();
    conc.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    let ent: std::collections::HashMap<&str, f64> = m
        .utterance_entropy_by_channel
        .iter()
        .map(|(k, v)| (k.as_str(), *v))
        .collect();

    let _ = writeln!(md, "## チャネル別発言エントロピー / 集中度 (上位{top})\n");
    let _ = writeln!(md, "| チャネル | エントロピー(bit) | 正規化集中度η |");
    let _ = writeln!(md, "|----------|-------------------|----------------|");
    for (name, eta) in conc.iter().take(top) {
        let h = ent.get(name.as_str()).copied().unwrap_or(0.0);
        let _ = writeln!(md, "| {name} | {h:.4} | {eta:.4} |");
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");

    write_files(dir, "H3", label, n_channels, n_messages, m, &md)
}

/// Write `report.md` + `metrics.json` for the H4 hypothesis．
pub fn write_h4_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    m: &H4Metrics,
) -> Result<()> {
    let mut md = header("H4: 擬似合意レポート", label, n_channels, n_messages);
    let _ = writeln!(md, "## 指標\n");
    let _ = writeln!(md, "| 指標 | 値 | 解釈 |");
    let _ = writeln!(md, "|------|----|------|");
    let _ = writeln!(
        md,
        "| 表層同意率 | {:.4} | 高いほど表面的な同意表現が多く本音が見えにくい可能性 |",
        m.surface_agreement_rate
    );
    let ppsd = match m.public_private_sentiment_delta {
        Some(v) => format!("{:.4}", v),
        None => NA_NLP.to_string(),
    };
    let _ = writeln!(
        md,
        "| 公私感情差 | {ppsd} | 公開系チャネルと雑談系チャネルの平均感情極性差 |"
    );
    let _ = writeln!(
        md,
        "| 会議後反論率 | {:.4} | 公開合意の後に別チャネルで反論する割合 |",
        m.post_meeting_dissent_rate
    );
    let _ = writeln!(
        md,
        "| 実行遅延(時間) | {:.2} | コミットメントから完了言及までの中央値 |",
        m.execution_delay_hours
    );
    let rtd = match m.reaction_text_disagreement {
        Some(v) => format!("{:.4}", v),
        None => NA_NLP.to_string(),
    };
    let _ = writeln!(
        md,
        "| リアクション/本文不一致 | {rtd} | 賛同リアクション付き発言のうち本文が否定的な割合 |\n"
    );

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");

    write_files(dir, "H4", label, n_channels, n_messages, m, &md)
}

/// Write `report.md` + `metrics.json` for the H5 hypothesis．
pub fn write_h5_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    m: &H5Metrics,
    top: usize,
) -> Result<()> {
    let mut md = header("H5: 探索能力レポート", label, n_channels, n_messages);
    let _ = writeln!(md, "## 主要指標\n");
    let _ = writeln!(md, "| 指標 | 値 | 解釈 |");
    let _ = writeln!(md, "|------|----|------|");
    let psd = match m.proposal_semantic_diversity {
        Some(v) => format!("{:.4}", v),
        None => NA_NLP.to_string(),
    };
    let _ = writeln!(
        md,
        "| 提案意味多様性 | {psd} | スレッド内提案発言の埋め込み共分散trace平均 |"
    );
    let _ = writeln!(
        md,
        "| 仮説保持期間(時間) | {:.2} | 未確定マーカ付きスレッドの存続時間の中央値 |",
        m.hypothesis_retention_period_hours
    );
    let _ = writeln!(
        md,
        "| 未解決スレッド比 | {:.4} | 結論マーカが付かないスレッドの割合 |",
        m.unresolved_thread_ratio
    );
    let tcc = match &m.topic_cluster_count_monthly {
        Some(v) => format!("{}ヶ月分", v.len()),
        None => NA_NLP.to_string(),
    };
    let _ = writeln!(
        md,
        "| トピッククラスタ数(月次) | {tcc} | 月次の意味クラスタ数 |\n"
    );

    let _ = writeln!(md, "## 新規語彙率(月次, 直近{top}ヶ月)\n");
    let _ = writeln!(md, "| 月 | 新規語彙率 |");
    let _ = writeln!(md, "|----|------------|");
    let n = m.novel_vocabulary_rate_monthly.len();
    let start = n.saturating_sub(top);
    for (month, rate) in &m.novel_vocabulary_rate_monthly[start..] {
        let _ = writeln!(md, "| {month} | {rate:.4} |");
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");

    write_files(dir, "H5", label, n_channels, n_messages, m, &md)
}

/// Write `report.md` + `metrics.json` for the H1 hypothesis．
pub fn write_h1_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    m: &H1Metrics,
    nlp_used: bool,
) -> Result<()> {
    let mut md = header(
        "H1: 議論は探索か正当化か レポート",
        label,
        n_channels,
        n_messages,
    );
    let _ = writeln!(md, "## 指標\n");
    let _ = writeln!(md, "| 指標 | 値 | 解釈 |");
    let _ = writeln!(md, "|------|----|------|");
    let dcr = if nlp_used {
        format!("{:.4}", m.decision_change_rate)
    } else {
        NA_NLP.to_string()
    };
    let _ = writeln!(
        md,
        "| 決定変更率 | {dcr} | スレッド冒頭の提案と結論が乖離した割合 |"
    );
    let ipr = if nlp_used {
        format!("{:.4}", m.initial_proposal_regression)
    } else {
        NA_NLP.to_string()
    };
    let _ = writeln!(
        md,
        "| 初期提案回帰率 | {ipr} | 一旦発散した後に冒頭提案へ回帰した割合 |"
    );
    let _ = writeln!(
        md,
        "| 管理職発言の沈黙率 | {:.4} | 管理職発言のうち24h以内に返信0だった割合 |",
        m.silence_after_manager.manager_post_silence_rate
    );
    let _ = writeln!(
        md,
        "| スタッフ発言の沈黙率 | {:.4} | スタッフ発言のうち24h以内に返信0だった割合 |",
        m.silence_after_manager.staff_post_silence_rate
    );
    let _ = writeln!(
        md,
        "| 沈黙比(管理職/スタッフ) | {:.4} | 1超で管理職発言の方が沈黙されやすい (沈黙仮説) |",
        m.silence_after_manager.ratio
    );
    let _ = writeln!(
        md,
        "| 反対意見の収束速度(分) | {:.2} | 反対発言が出尽くすまでの時間の中央値 |",
        m.dissent_convergence_speed_minutes
    );
    let _ = writeln!(
        md,
        "| スレッド数 | {} | 集計対象スレッド数（2件以上） |\n",
        m.thread_count
    );

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");

    write_files(dir, "H1", label, n_channels, n_messages, m, &md)
}

/// Write the **integrated** H1–H5 report．
pub fn write_comm_report(
    dir: &Path,
    label: &str,
    n_channels: usize,
    n_messages: usize,
    rep: &CommReport,
    nlp_used: bool,
) -> Result<()> {
    let mut md = String::new();
    let _ = writeln!(md, "# 組織コミュニケーション分析レポート\n");
    let _ = writeln!(md, "- 期間: {label}");
    let _ = writeln!(md, "- 対象チャネル: {n_channels}個");
    let _ = writeln!(md, "- 対象メッセージ: {n_messages}件");
    let _ = writeln!(md, "- 設定ハッシュ: {}", rep.config_hash);
    let _ = writeln!(md, "- run_id: {}\n", rep.run_id);

    let _ = writeln!(md, "## サマリ\n");
    let _ = writeln!(
        md,
        "- 健全度スコア: {:.2} / 1.0\n",
        rep.summary.overall_health_score
    );
    let _ = writeln!(md, "### 🚨 赤信号\n");
    if rep.summary.red_flags.is_empty() {
        let _ = writeln!(md, "- なし");
    } else {
        for f in &rep.summary.red_flags {
            let _ = writeln!(md, "- {f}");
        }
    }
    let _ = writeln!(md, "\n### ⚠️ 黄信号\n");
    if rep.summary.yellow_flags.is_empty() {
        let _ = writeln!(md, "- なし");
    } else {
        for f in &rep.summary.yellow_flags {
            let _ = writeln!(md, "- {f}");
        }
    }
    let _ = writeln!(md, "\n### 🟢 緑信号\n");
    if rep.summary.green_signals.is_empty() {
        let _ = writeln!(md, "- なし");
    } else {
        for g in &rep.summary.green_signals {
            let _ = writeln!(md, "- {g}");
        }
    }
    let _ = writeln!(md);

    let na = "（未選択）";

    let _ = writeln!(md, "## H1: 議論は探索か正当化か\n");
    match &rep.h1 {
        Some(m) => {
            let dcr = if nlp_used {
                format!("{:.4}", m.decision_change_rate)
            } else {
                NA_NLP.to_string()
            };
            let ipr = if nlp_used {
                format!("{:.4}", m.initial_proposal_regression)
            } else {
                NA_NLP.to_string()
            };
            let _ = writeln!(md, "| 指標 | 値 |");
            let _ = writeln!(md, "|------|----|");
            let _ = writeln!(md, "| 決定変更率 | {dcr} |");
            let _ = writeln!(md, "| 初期提案回帰率 | {ipr} |");
            let _ = writeln!(
                md,
                "| 沈黙比(管理職/スタッフ) | {:.4} |",
                m.silence_after_manager.ratio
            );
            let _ = writeln!(
                md,
                "| 反対意見の収束速度(分) | {:.2} |",
                m.dissent_convergence_speed_minutes
            );
            let _ = writeln!(md, "| スレッド数 | {} |\n", m.thread_count);
            let _ = writeln!(
                md,
                "沈黙比が1を超える場合，管理職発言の方が沈黙されやすい (沈黙仮説)．\n"
            );
        }
        None => {
            let _ = writeln!(md, "{na}\n");
        }
    }

    let _ = writeln!(md, "## H2: 心理的安全性\n");
    match &rep.h2 {
        Some(m) => {
            let _ = writeln!(md, "| 指標 | 値 |");
            let _ = writeln!(md, "|------|----|");
            let _ = writeln!(md, "| ヘッジ表現率 | {:.4} |", m.hedging_rate);
            let _ = writeln!(md, "| 自己防衛表現率 | {:.4} |", m.self_defense_rate);
            let _ = writeln!(md, "| 未完結発話率 | {:.4} |", m.incomplete_utterance_rate);
            let _ = writeln!(
                md,
                "| エスカレーション遅延(分) | {:.2} |",
                m.escalation_delay_minutes
            );
            let _ = writeln!(md, "| サンプル数 | {} |\n", m.sample_size);
            let _ = writeln!(md, "高いほど自己防衛的で心理的安全性が低い可能性．\n");
        }
        None => {
            let _ = writeln!(md, "{na}\n");
        }
    }

    let _ = writeln!(md, "## H3: 権力勾配\n");
    match &rep.h3 {
        Some(m) => {
            let _ = writeln!(md, "| 指標 | 値 |");
            let _ = writeln!(md, "|------|----|");
            let _ = writeln!(md, "| 返信集中Gini | {:.4} |", m.reply_concentration_gini);
            let _ = writeln!(md, "| マネージャ反応率 | {:.4} |", m.manager_reaction_rate);
            let _ = writeln!(md, "| 階層スコア | {:.4} |", m.hierarchy_score);
            let _ = writeln!(
                md,
                "| PageRank上位の管理職占有率 | {:.4} |\n",
                m.pagerank_topk_manager_share
            );
            let _ = writeln!(md, "1に近い集中指標は権力の偏りを示唆．\n");
        }
        None => {
            let _ = writeln!(md, "{na}\n");
        }
    }

    let _ = writeln!(md, "## H4: 擬似合意\n");
    match &rep.h4 {
        Some(m) => {
            let ppsd = match m.public_private_sentiment_delta {
                Some(v) => format!("{:.4}", v),
                None => NA_NLP.to_string(),
            };
            let rtd = match m.reaction_text_disagreement {
                Some(v) => format!("{:.4}", v),
                None => NA_NLP.to_string(),
            };
            let _ = writeln!(md, "| 指標 | 値 |");
            let _ = writeln!(md, "|------|----|");
            let _ = writeln!(md, "| 表層同意率 | {:.4} |", m.surface_agreement_rate);
            let _ = writeln!(md, "| 公私感情差 | {ppsd} |");
            let _ = writeln!(md, "| 会議後反論率 | {:.4} |", m.post_meeting_dissent_rate);
            let _ = writeln!(md, "| 実行遅延(時間) | {:.2} |", m.execution_delay_hours);
            let _ = writeln!(md, "| リアクション/本文不一致 | {rtd} |\n");
            let _ = writeln!(md, "表層同意率が高いほど本音が見えにくい可能性．\n");
        }
        None => {
            let _ = writeln!(md, "{na}\n");
        }
    }

    let _ = writeln!(md, "## H5: 探索能力\n");
    match &rep.h5 {
        Some(m) => {
            let psd = match m.proposal_semantic_diversity {
                Some(v) => format!("{:.4}", v),
                None => NA_NLP.to_string(),
            };
            let tcc = match &m.topic_cluster_count_monthly {
                Some(v) => format!("{}ヶ月分", v.len()),
                None => NA_NLP.to_string(),
            };
            let _ = writeln!(md, "| 指標 | 値 |");
            let _ = writeln!(md, "|------|----|");
            let _ = writeln!(md, "| 提案意味多様性 | {psd} |");
            let _ = writeln!(
                md,
                "| 仮説保持期間(時間) | {:.2} |",
                m.hypothesis_retention_period_hours
            );
            let _ = writeln!(
                md,
                "| 未解決スレッド比 | {:.4} |",
                m.unresolved_thread_ratio
            );
            let _ = writeln!(md, "| トピッククラスタ数(月次) | {tcc} |\n");
            let _ = writeln!(md, "未解決スレッド比が高いほど発散的．\n");
        }
        None => {
            let _ = writeln!(md, "{na}\n");
        }
    }

    let _ = writeln!(md, "## 倫理的注意事項\n");
    let _ = writeln!(md, "{ETHICS_NOTE}");
    let _ = writeln!(md, "本レポートは集計値のみ．個人評価・懲罰利用禁止．");

    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("report.md"), &md)?;
    let pretty = serde_json::to_string_pretty(rep)
        .map_err(|e| crate::error::CommError::Config(e.to_string()))?;
    std::fs::write(dir.join("metrics.json"), pretty)?;
    Ok(())
}

/// Write the only **per-user** artifact: `dir/tables/h3_pagerank.csv`．
pub fn write_h3_pagerank_csv(
    dir: &Path,
    graph: &ReplyGraph,
    anon: &Anonymizer,
    top_n: usize,
) -> Result<bool> {
    if graph.node_count() == 0 || top_n == 0 {
        return Ok(false);
    }
    let mut pr = graph.pagerank(0.85, 100);
    pr.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    pr.truncate(top_n);
    if pr.is_empty() {
        return Ok(false);
    }
    let tables = dir.join("tables");
    std::fs::create_dir_all(&tables)?;
    let mut csv = String::from("anon_user,role,pagerank\n");
    for (uid, score) in &pr {
        let role = graph
            .node_role(uid)
            .map(|r| r.as_str())
            .unwrap_or("unknown");
        let _ = writeln!(csv, "{},{},{:.6}", anon.anon(uid), role, score);
    }
    std::fs::write(tables.join("h3_pagerank.csv"), csv)?;
    Ok(true)
}

/// Generate all runtime assets and append a `## 図表` section to the existing
/// `report.md`．Returns the relative paths of the generated assets．
pub fn finalize_report_assets(
    dir: &Path,
    rep: &CommReport,
    graph: Option<&ReplyGraph>,
    anon: &Anonymizer,
    top_n: usize,
) -> Result<Vec<String>> {
    let mut assets: Vec<String> = Vec::new();
    let figdir = dir.join("figures");
    std::fs::create_dir_all(&figdir)?;

    if let Some(h3) = &rep.h3 {
        let p = figdir.join("h3_entropy_by_channel.svg");
        if figures::entropy_by_channel_svg(&p, &h3.normalized_concentration, top_n.max(1))? {
            assets.push("figures/h3_entropy_by_channel.svg".to_string());
        }
    }
    if let Some(h5) = &rep.h5 {
        let p = figdir.join("h5_novel_vocab.svg");
        if figures::novel_vocab_svg(&p, &h5.novel_vocabulary_rate_monthly)? {
            assets.push("figures/h5_novel_vocab.svg".to_string());
        }
    }
    {
        let p = figdir.join("summary_health.svg");
        if figures::health_summary_svg(&p, &rep.summary)? {
            assets.push("figures/summary_health.svg".to_string());
        }
    }

    let mut csv_written = false;
    if let Some(g) = graph {
        if write_h3_pagerank_csv(dir, g, anon, top_n.max(1))? {
            assets.push("tables/h3_pagerank.csv".to_string());
            csv_written = true;
        }
    }

    anon.write_map(dir)?;
    if anon.is_enabled()
        && dir.join("anonymize_map.tsv").exists()
        && !assets.iter().any(|a| a == "anonymize_map.tsv")
    {
        assets.push("anonymize_map.tsv".to_string());
    }

    let md_path = dir.join("report.md");
    let mut md = std::fs::read_to_string(&md_path)?;
    let mut section = String::new();
    let _ = writeln!(section, "\n## 図表\n");
    for a in &assets {
        if a.ends_with(".svg") {
            let _ = writeln!(section, "![[{a}]]");
        }
    }
    if csv_written {
        let _ = writeln!(
            section,
            "- 個別ユーザ集計（匿名化済）: ![[tables/h3_pagerank.csv]]"
        );
    }
    if !anon.is_enabled() {
        let _ = writeln!(
            section,
            "\n> ⚠️ 非匿名化モード: このレポートには生のユーザ ID が含まれます（--no-anonymize 指定）．取扱注意．"
        );
    }
    md.push_str(&section);
    std::fs::write(&md_path, md)?;

    Ok(assets)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::DissentBias;

    #[test]
    fn test_write_h2_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let m = H2Metrics {
            hedging_rate: 0.25,
            self_defense_rate: 0.1,
            incomplete_utterance_rate: 0.05,
            escalation_delay_minutes: 12.5,
            dm_dependency_ratio: None,
            sample_size: 100,
        };
        write_h2_report(dir.path(), "all", 3, 100, &m).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("H2: 心理的安全性レポート"));
        assert!(md.contains("倫理的注意事項"));
        assert!(!md.contains("Claude"));
        let json = std::fs::read_to_string(dir.path().join("metrics.json")).unwrap();
        assert!(json.contains("\"hypothesis\": \"H2\""));
    }

    #[test]
    fn test_write_h3_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let m = H3Metrics {
            utterance_entropy_by_channel: vec![("general".into(), 1.5)],
            normalized_concentration: vec![("general".into(), 0.3)],
            reply_concentration_gini: 0.4,
            manager_reaction_rate: 0.2,
            dissent_target_bias: DissentBias {
                to_manager: 0.1,
                to_staff: 0.2,
                ratio_staff_to_manager: 2.0,
            },
            hierarchy_score: 0.9,
            pagerank_topk_manager_share: 0.5,
        };
        write_h3_report(dir.path(), "all", 1, 50, &m, 20).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("H3: 権力勾配レポート"));
        assert!(md.contains("general"));
    }

    #[test]
    fn test_write_h4_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let m = H4Metrics {
            surface_agreement_rate: 0.3,
            public_private_sentiment_delta: None,
            post_meeting_dissent_rate: 0.1,
            execution_delay_hours: 5.5,
            reaction_text_disagreement: None,
        };
        write_h4_report(dir.path(), "all", 2, 80, &m).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("H4: 擬似合意レポート"));
        assert!(md.contains("NLP sidecar 無効/未起動"));
    }

    #[test]
    fn test_write_h5_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let m = H5Metrics {
            proposal_semantic_diversity: None,
            hypothesis_retention_period_hours: 36.0,
            unresolved_thread_ratio: 0.4,
            novel_vocabulary_rate_monthly: vec![
                ("2025-01".into(), 1.0),
                ("2025-02".into(), 0.6),
                ("2025-03".into(), 0.3),
            ],
            topic_cluster_count_monthly: None,
        };
        write_h5_report(dir.path(), "all", 4, 120, &m, 2).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("H5: 探索能力レポート"));
        assert!(md.contains("2025-02"));
        assert!(md.contains("2025-03"));
        assert!(!md.contains("2025-01"));
    }

    fn sample_h1() -> H1Metrics {
        H1Metrics {
            decision_change_rate: 0.3,
            initial_proposal_regression: 0.1,
            silence_after_manager: crate::models::SilenceRatio {
                manager_post_silence_rate: 0.4,
                staff_post_silence_rate: 0.2,
                ratio: 2.0,
            },
            dissent_convergence_speed_minutes: 45.0,
            thread_count: 12,
        }
    }

    #[test]
    fn test_write_h1_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let m = sample_h1();
        write_h1_report(dir.path(), "all", 3, 100, &m, false).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("H1: 議論は探索か正当化か レポート"));
        assert!(md.contains("NLP sidecar 無効/未起動"));

        let dir2 = tempfile::tempdir().unwrap();
        write_h1_report(dir2.path(), "all", 3, 100, &m, true).unwrap();
        let md2 = std::fs::read_to_string(dir2.path().join("report.md")).unwrap();
        assert!(md2.contains("0.3000"));
        assert!(!md2.contains("NLP sidecar 無効/未起動"));
    }

    #[test]
    fn test_write_comm_report_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let rep = CommReport {
            run_id: "run-abc".into(),
            config_hash: "deadbeef".into(),
            period: crate::models::PeriodSpec::default(),
            h1: Some(sample_h1()),
            h2: None,
            h3: None,
            h4: Some(H4Metrics {
                surface_agreement_rate: 0.4,
                public_private_sentiment_delta: None,
                post_meeting_dissent_rate: 0.1,
                execution_delay_hours: 5.0,
                reaction_text_disagreement: None,
            }),
            h5: None,
            summary: crate::models::ReportSummary {
                overall_health_score: 0.42,
                red_flags: vec!["表層同意率 40% (基準 < 15%)".into()],
                yellow_flags: vec![],
                green_signals: vec![],
            },
        };
        write_comm_report(dir.path(), "FY2025-Q1", 5, 200, &rep, false).unwrap();
        let md = std::fs::read_to_string(dir.path().join("report.md")).unwrap();
        assert!(md.contains("# 組織コミュニケーション分析レポート"));
        assert!(md.contains("## サマリ"));
        assert!(md.contains("- run_id: run-abc"));
        assert!(md.contains("## H1: 議論は探索か正当化か"));
        assert!(md.contains("（未選択）"));
        assert!(md.contains("## 倫理的注意事項"));
        assert!(!md.contains("Claude"));
    }

    // ---- Anonymization audit: no raw-ID-leak property -----------------------

    use crate::config::{CommConfig, RoleEntry};
    use crate::graph::ReplyGraph as RG;
    use crate::types::{AnalysisInput, Message};
    use chrono::{DateTime, TimeZone, Utc};

    fn ts(s: i64) -> DateTime<Utc> {
        Utc.timestamp_opt(s, 0).single().unwrap()
    }

    fn audit_msg(
        ch: &str,
        id: &str,
        u: &str,
        text: &str,
        t: DateTime<Utc>,
        root: Option<&str>,
    ) -> Message {
        Message {
            id: id.to_string(),
            channel_id: ch.to_string(),
            author_id: u.to_string(),
            text: text.to_string(),
            timestamp: t,
            thread_root_id: root.map(String::from),
            reaction_count: 0,
        }
    }

    fn audit_report() -> (CommReport, RG) {
        let mut cfg = CommConfig::default();
        cfg.roles.push(RoleEntry {
            user_id: "USER_ALICE".to_string(),
            role: crate::models::Role::Manager,
            seniority_level: 4,
            team: None,
        });
        let msgs = vec![
            audit_msg(
                "C1",
                "M1",
                "USER_ALICE",
                "ルート提案です",
                ts(100),
                Some("M1"),
            ),
            audit_msg(
                "C1",
                "M2",
                "USER_BOB",
                "しかし別の見方があります",
                ts(110),
                Some("M1"),
            ),
            audit_msg(
                "C1",
                "M3",
                "USER_CAROL",
                "確認しました賛成です",
                ts(120),
                Some("M1"),
            ),
            audit_msg("C1", "M4", "USER_BOB", "通常発言", ts(130), None),
            audit_msg("C2", "M5", "USER_CAROL", "別ルート", ts(200), Some("M5")),
            audit_msg("C2", "M6", "USER_ALICE", "返信します", ts(210), Some("M5")),
        ];
        let channels = vec![
            crate::types::Channel {
                id: "C1".into(),
                name: "general".into(),
                category: None,
                is_decision_channel: false,
            },
            crate::types::Channel {
                id: "C2".into(),
                name: "random".into(),
                category: None,
                is_decision_channel: false,
            },
        ];
        let input = AnalysisInput {
            messages: &msgs,
            channels: &channels,
            users: &[],
            reactions: &[],
            config: &cfg,
        };
        let h3 = crate::compute_h3(&input).unwrap();
        let h5 = crate::compute_h5(&input, &crate::WhitespaceMorphology).unwrap();
        let summary = crate::build_summary(None, None, Some(&h3), None, Some(&h5));
        let rep = CommReport {
            run_id: "run-audit".into(),
            config_hash: "cfghash".into(),
            period: crate::models::PeriodSpec::default(),
            h1: None,
            h2: None,
            h3: Some(h3),
            h4: None,
            h5: Some(h5),
            summary,
        };
        let graph = RG::build(&msgs, &cfg);
        (rep, graph)
    }

    #[test]
    fn test_finalize_report_assets_no_raw_id_leak() {
        use regex::Regex;
        let (rep, graph) = audit_report();

        let dir = tempfile::tempdir().unwrap();
        write_comm_report(dir.path(), "all", 2, 6, &rep, false).unwrap();

        let anon = Anonymizer::with_salt(true, [7u8; 16]);
        let assets = finalize_report_assets(dir.path(), &rep, Some(&graph), &anon, 20).unwrap();

        assert!(dir.path().join("report.md").exists());
        assert!(dir.path().join("metrics.json").exists());
        assert!(dir.path().join("tables/h3_pagerank.csv").exists());
        let fig_count = std::fs::read_dir(dir.path().join("figures"))
            .unwrap()
            .filter(|e| e.as_ref().unwrap().path().extension().is_some())
            .count();
        assert!(fig_count >= 1);
        assert!(assets.iter().any(|a| a == "tables/h3_pagerank.csv"));

        // No raw platform-ID leak (the IDs in this audit use the test prefix
        // `USER_<NAME>`; matching that exact shape).
        let id_re = Regex::new(r"USER_[A-Z]+").unwrap();
        let mut texts: Vec<String> = vec![
            std::fs::read_to_string(dir.path().join("report.md")).unwrap(),
            std::fs::read_to_string(dir.path().join("metrics.json")).unwrap(),
            std::fs::read_to_string(dir.path().join("tables/h3_pagerank.csv")).unwrap(),
        ];
        for e in std::fs::read_dir(dir.path().join("figures")).unwrap() {
            texts.push(std::fs::read_to_string(e.unwrap().path()).unwrap());
        }
        for t in &texts {
            assert!(
                !id_re.is_match(t),
                "raw platform-style ID leaked into an artifact"
            );
        }

        let map_body = std::fs::read_to_string(dir.path().join("anonymize_map.tsv")).unwrap();
        let anon_re = Regex::new(r"^ANON-[0-9a-f]{6}$").unwrap();
        let mut anons = std::collections::HashSet::new();
        let mut origs = std::collections::HashSet::new();
        let mut rows = 0usize;
        for line in map_body.lines() {
            if line.starts_with('#') {
                continue;
            }
            let (a, o) = line.split_once('\t').unwrap();
            assert!(anon_re.is_match(a));
            assert!(anons.insert(a.to_string()));
            assert!(origs.insert(o.to_string()));
            rows += 1;
        }
        assert_eq!(rows, 3);
        assert_eq!(anons.len(), 3);
        assert_eq!(origs.len(), 3);
        assert!(anons.contains(&anon.anon("USER_ALICE")));

        // ---- disabled (--no-anonymize) ----
        let dir2 = tempfile::tempdir().unwrap();
        write_comm_report(dir2.path(), "all", 2, 6, &rep, false).unwrap();
        let anon_off = Anonymizer::new(false);
        finalize_report_assets(dir2.path(), &rep, Some(&graph), &anon_off, 20).unwrap();
        let csv2 = std::fs::read_to_string(dir2.path().join("tables/h3_pagerank.csv")).unwrap();
        assert!(id_re.is_match(&csv2), "raw IDs expected when disabled");
        let md2 = std::fs::read_to_string(dir2.path().join("report.md")).unwrap();
        assert!(md2.contains("非匿名化モード"));
        assert!(!dir2.path().join("anonymize_map.tsv").exists());
    }
}
